GET http://localhost:3000/users 

###

POST http://localhost:3000/users
Content-Type: application/json


{
    "firstName": "Lulo",
    "lastName": "Kolisi",
    "email": "lulokolisi@gmail.com",
    "password": "password",
    "roles": "Manager"
}


###

POST http://localhost:3000/users/login
Content-Type: application/json


{
    "email": "lulokolisi@gmail.com",
    "password": "password"
}